services:
  database:
    image: postgres:16.3
    container_name: "recipe_posgresql"
    restart: always
    environment:
      - POSTGRES_USER=phaz
      - POSTGRES_PASSWORD=supersecr3t
      - POSTGRES_DB=recipedb
    volumes:
    - postgres:/var/lib/postgresql/data
    ports:
      - '5469:5432'

  adminer:
    image: adminer
    restart: always
    ports:
      - '8069:8080'

volumes:
  postgres:
