services:
  database:
    image: postgres:16.3
    container_name: "recipe_posgresql"
    restart: always
    environment:
      - POSTGRES_USER=phaz
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=recipedb
    volumes:
    - postgres:/var/lib/postgresql/data
    ports:
      - '5469:5432'

  pgadmin:
      container_name: "recipedb_pgadmin"
      image: dpage/pgadmin4
      restart: always
      environment:
          PGADMIN_DEFAULT_EMAIL: phaz@admin.com
          PGADMIN_DEFAULT_PASSWORD: secret
          #PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: true
          PGADMIN_CONFIG_CONSOLE_LOG_LEVEL: 10
      ports:
        - '8069:80'

volumes:
  postgres:
